export {default as Home} from "./home/Home"
export {default as About} from "./about/About"
export {default as Articles} from "./articles/Articles"
export {default as IPassets} from "./ipAssets/IPassets"
export {default as UserProfile} from "./profile/UserProfile"
export {default as SignUp} from "../signup/SignUp"